/* AUTO-GENERATED by build-images.js — do not edit by hand.
   Run "node javascript/build-images.js" after changing files in images/. */
window.PORTFOLIO = {
  "categories": [
    {
      "slug": "visual-development",
      "title": "Visual Development",
      "page": "/html/concept-art.html",
      "cover": "/images/VISUAL DEVELOPMENT/1. YOKAI/1 YOKAI.avif",
      "projects": [
        {
          "slug": "yokai",
          "name": "1. YOKAI",
          "title": "Yokai",
          "dir": "/images/VISUAL DEVELOPMENT/1. YOKAI",
          "preview": [
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/1 YOKAI.avif",
              "type": "image",
              "name": "1 YOKAI.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/2 YOKAI.avif",
              "type": "image",
              "name": "2 YOKAI.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/3 YOKAI.avif",
              "type": "image",
              "name": "3 YOKAI.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/4 YOKAI.avif",
              "type": "image",
              "name": "4 YOKAI.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/5 YOKAI.avif",
              "type": "image",
              "name": "5 YOKAI.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/6 YOKAI.avif",
              "type": "image",
              "name": "6 YOKAI.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/7 YOKAI.avif",
              "type": "image",
              "name": "7 YOKAI.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/8 YOKAI.avif",
              "type": "image",
              "name": "8 YOKAI.avif",
              "major": 8,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/9 YOKAI.avif",
              "type": "image",
              "name": "9 YOKAI.avif",
              "major": 9,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/10 YOKAI.avif",
              "type": "image",
              "name": "10 YOKAI.avif",
              "major": 10,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/11 YOKAI.avif",
              "type": "image",
              "name": "11 YOKAI.avif",
              "major": 11,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/12 YOKAI.avif",
              "type": "image",
              "name": "12 YOKAI.avif",
              "major": 12,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/13 YOKAI.avif",
              "type": "image",
              "name": "13 YOKAI.avif",
              "major": 13,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/14 YOKAI.avif",
              "type": "image",
              "name": "14 YOKAI.avif",
              "major": 14,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/15 YOKAI.avif",
              "type": "image",
              "name": "15 YOKAI.avif",
              "major": 15,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/16 YOKAI.avif",
              "type": "image",
              "name": "16 YOKAI.avif",
              "major": 16,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/17 YOKAI.avif",
              "type": "image",
              "name": "17 YOKAI.avif",
              "major": 17,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/18 YOKAI.avif",
              "type": "image",
              "name": "18 YOKAI.avif",
              "major": 18,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/19 YOKAI.avif",
              "type": "image",
              "name": "19 YOKAI.avif",
              "major": 19,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/20 YOKAI.avif",
              "type": "image",
              "name": "20 YOKAI.avif",
              "major": 20,
              "minor": 0
            }
          ],
          "count": 20,
          "items": [
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/1 YOKAI.avif",
              "type": "image",
              "name": "1 YOKAI.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/2 YOKAI.avif",
              "type": "image",
              "name": "2 YOKAI.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/3 YOKAI.avif",
              "type": "image",
              "name": "3 YOKAI.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/4 YOKAI.avif",
              "type": "image",
              "name": "4 YOKAI.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/5 YOKAI.avif",
              "type": "image",
              "name": "5 YOKAI.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/6 YOKAI.avif",
              "type": "image",
              "name": "6 YOKAI.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/7 YOKAI.avif",
              "type": "image",
              "name": "7 YOKAI.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/8 YOKAI.avif",
              "type": "image",
              "name": "8 YOKAI.avif",
              "major": 8,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/9 YOKAI.avif",
              "type": "image",
              "name": "9 YOKAI.avif",
              "major": 9,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/10 YOKAI.avif",
              "type": "image",
              "name": "10 YOKAI.avif",
              "major": 10,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/11 YOKAI.avif",
              "type": "image",
              "name": "11 YOKAI.avif",
              "major": 11,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/12 YOKAI.avif",
              "type": "image",
              "name": "12 YOKAI.avif",
              "major": 12,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/13 YOKAI.avif",
              "type": "image",
              "name": "13 YOKAI.avif",
              "major": 13,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/14 YOKAI.avif",
              "type": "image",
              "name": "14 YOKAI.avif",
              "major": 14,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/15 YOKAI.avif",
              "type": "image",
              "name": "15 YOKAI.avif",
              "major": 15,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/16 YOKAI.avif",
              "type": "image",
              "name": "16 YOKAI.avif",
              "major": 16,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/17 YOKAI.avif",
              "type": "image",
              "name": "17 YOKAI.avif",
              "major": 17,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/18 YOKAI.avif",
              "type": "image",
              "name": "18 YOKAI.avif",
              "major": 18,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/19 YOKAI.avif",
              "type": "image",
              "name": "19 YOKAI.avif",
              "major": 19,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/1. YOKAI/20 YOKAI.avif",
              "type": "image",
              "name": "20 YOKAI.avif",
              "major": 20,
              "minor": 0
            }
          ],
          "groups": []
        },
        {
          "slug": "a-un-passo-dal-cielo",
          "name": "2. A UN PASSO DAL CIELO",
          "title": "A Un Passo Dal Cielo",
          "dir": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO",
          "preview": [
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/1 A un passo dal cielo.avif",
              "type": "image",
              "name": "1 A un passo dal cielo.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/2 A un passo dal cielo.avif",
              "type": "image",
              "name": "2 A un passo dal cielo.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/3 A un passo dal cielo.avif",
              "type": "image",
              "name": "3 A un passo dal cielo.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/4 A un passo dal cielo.avif",
              "type": "image",
              "name": "4 A un passo dal cielo.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/5 A un passo dal cielo.avif",
              "type": "image",
              "name": "5 A un passo dal cielo.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/6 A un passo dal cielo.avif",
              "type": "image",
              "name": "6 A un passo dal cielo.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/7 A un passo dal cielo.avif",
              "type": "image",
              "name": "7 A un passo dal cielo.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/8 A un passo dal cielo.avif",
              "type": "image",
              "name": "8 A un passo dal cielo.avif",
              "major": 8,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/9 A un passo dal cielo.avif",
              "type": "image",
              "name": "9 A un passo dal cielo.avif",
              "major": 9,
              "minor": 0
            }
          ],
          "count": 26,
          "items": [
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/1 A un passo dal cielo.avif",
              "type": "image",
              "name": "1 A un passo dal cielo.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/2 A un passo dal cielo.avif",
              "type": "image",
              "name": "2 A un passo dal cielo.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/3 A un passo dal cielo.avif",
              "type": "image",
              "name": "3 A un passo dal cielo.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/4 A un passo dal cielo.avif",
              "type": "image",
              "name": "4 A un passo dal cielo.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/5 A un passo dal cielo.avif",
              "type": "image",
              "name": "5 A un passo dal cielo.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/6 A un passo dal cielo.avif",
              "type": "image",
              "name": "6 A un passo dal cielo.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/7 A un passo dal cielo.avif",
              "type": "image",
              "name": "7 A un passo dal cielo.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/8 A un passo dal cielo.avif",
              "type": "image",
              "name": "8 A un passo dal cielo.avif",
              "major": 8,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/9 A un passo dal cielo.avif",
              "type": "image",
              "name": "9 A un passo dal cielo.avif",
              "major": 9,
              "minor": 0
            }
          ],
          "groups": [
            {
              "name": "storyboard",
              "title": "Storyboard",
              "items": [
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/1 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "1 a un passo dal cielo.avif",
                  "major": 1,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/2 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "2 a un passo dal cielo.avif",
                  "major": 2,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/3 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "3 a un passo dal cielo.avif",
                  "major": 3,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/4 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "4 a un passo dal cielo.avif",
                  "major": 4,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/5 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "5 a un passo dal cielo.avif",
                  "major": 5,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/6 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "6 a un passo dal cielo.avif",
                  "major": 6,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/7 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "7 a un passo dal cielo.avif",
                  "major": 7,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/8 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "8 a un passo dal cielo.avif",
                  "major": 8,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/9 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "9 a un passo dal cielo.avif",
                  "major": 9,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/10 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "10 a un passo dal cielo.avif",
                  "major": 10,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/11 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "11 a un passo dal cielo.avif",
                  "major": 11,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/12 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "12 a un passo dal cielo.avif",
                  "major": 12,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/13 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "13 a un passo dal cielo.avif",
                  "major": 13,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/14 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "14 a un passo dal cielo.avif",
                  "major": 14,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/15 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "15 a un passo dal cielo.avif",
                  "major": 15,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/16 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "16 a un passo dal cielo.avif",
                  "major": 16,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/2. A UN PASSO DAL CIELO/storyboard/17 a un passo dal cielo.avif",
                  "type": "image",
                  "name": "17 a un passo dal cielo.avif",
                  "major": 17,
                  "minor": 0
                }
              ]
            }
          ]
        },
        {
          "slug": "hansel-and-gretel-reinterpretation",
          "name": "3. HANSEL AND GRETEL REINTERPRETATION",
          "title": "Hansel And Gretel Reinterpretation",
          "dir": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION",
          "preview": [
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/1 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "1 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/2 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "2 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/3 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "3 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/4 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "4 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/5 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "5 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/6 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "6 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 6,
              "minor": 0
            }
          ],
          "count": 36,
          "items": [
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/1 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "1 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/2 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "2 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/3 HANSEL AND GRETEL REINTERPRETATION.avif",
              "type": "image",
              "name": "3 HANSEL AND GRETEL REINTERPRETATION.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/4 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "4 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/5 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "5 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/6 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "type": "video",
              "name": "6 HANSEL AND GRETEL REINTERPRETATION.mp4",
              "major": 6,
              "minor": 0
            }
          ],
          "groups": [
            {
              "name": "storyboard",
              "title": "Storyboard",
              "items": [
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/1 storyboard.avif",
                  "type": "image",
                  "name": "1 storyboard.avif",
                  "major": 1,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/2 storyboard.avif",
                  "type": "image",
                  "name": "2 storyboard.avif",
                  "major": 2,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/3 storyboard.avif",
                  "type": "image",
                  "name": "3 storyboard.avif",
                  "major": 3,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/4 storyboard.avif",
                  "type": "image",
                  "name": "4 storyboard.avif",
                  "major": 4,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/5 storyboard.avif",
                  "type": "image",
                  "name": "5 storyboard.avif",
                  "major": 5,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/6 storyboard.avif",
                  "type": "image",
                  "name": "6 storyboard.avif",
                  "major": 6,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/7 storyboard.avif",
                  "type": "image",
                  "name": "7 storyboard.avif",
                  "major": 7,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/8 storyboard.avif",
                  "type": "image",
                  "name": "8 storyboard.avif",
                  "major": 8,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/9 storyboard.avif",
                  "type": "image",
                  "name": "9 storyboard.avif",
                  "major": 9,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/10 storyboard.avif",
                  "type": "image",
                  "name": "10 storyboard.avif",
                  "major": 10,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/11 storyboard.avif",
                  "type": "image",
                  "name": "11 storyboard.avif",
                  "major": 11,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/12 storyboard.avif",
                  "type": "image",
                  "name": "12 storyboard.avif",
                  "major": 12,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/13 storyboard.avif",
                  "type": "image",
                  "name": "13 storyboard.avif",
                  "major": 13,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/14 storyboard.avif",
                  "type": "image",
                  "name": "14 storyboard.avif",
                  "major": 14,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/15 storyboard.avif",
                  "type": "image",
                  "name": "15 storyboard.avif",
                  "major": 15,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/16 storyboard.avif",
                  "type": "image",
                  "name": "16 storyboard.avif",
                  "major": 16,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/17 storyboard.avif",
                  "type": "image",
                  "name": "17 storyboard.avif",
                  "major": 17,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/18 storyboard.avif",
                  "type": "image",
                  "name": "18 storyboard.avif",
                  "major": 18,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/19 storyboard.avif",
                  "type": "image",
                  "name": "19 storyboard.avif",
                  "major": 19,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/20 storyboard.avif",
                  "type": "image",
                  "name": "20 storyboard.avif",
                  "major": 20,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/21 storyboard.avif",
                  "type": "image",
                  "name": "21 storyboard.avif",
                  "major": 21,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/22 storyboard.avif",
                  "type": "image",
                  "name": "22 storyboard.avif",
                  "major": 22,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/23 storyboard.avif",
                  "type": "image",
                  "name": "23 storyboard.avif",
                  "major": 23,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/24 storyboard.avif",
                  "type": "image",
                  "name": "24 storyboard.avif",
                  "major": 24,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/25 storyboard.avif",
                  "type": "image",
                  "name": "25 storyboard.avif",
                  "major": 25,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/26 storyboard.avif",
                  "type": "image",
                  "name": "26 storyboard.avif",
                  "major": 26,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/27 storyboard.avif",
                  "type": "image",
                  "name": "27 storyboard.avif",
                  "major": 27,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/28 storyboard.avif",
                  "type": "image",
                  "name": "28 storyboard.avif",
                  "major": 28,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/29 storyboard.avif",
                  "type": "image",
                  "name": "29 storyboard.avif",
                  "major": 29,
                  "minor": 0
                },
                {
                  "src": "/images/VISUAL DEVELOPMENT/3. HANSEL AND GRETEL REINTERPRETATION/storyboard/30 storyboard.avif",
                  "type": "image",
                  "name": "30 storyboard.avif",
                  "major": 30,
                  "minor": 0
                }
              ]
            }
          ]
        },
        {
          "slug": "miscellaneous",
          "name": "4. MISCELLANEOUS",
          "title": "Miscellaneous",
          "dir": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS",
          "preview": [
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/1 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "1 DETECTIVE SMOK.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/2 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "2 DETECTIVE SMOK.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/3 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "3 DETECTIVE SMOK.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/4 BG STUDY.avif",
              "type": "image",
              "name": "4 BG STUDY.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/5 BG STUDY.avif",
              "type": "image",
              "name": "5 BG STUDY.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/6 PENCIL SKETCHES.avif",
              "type": "image",
              "name": "6 PENCIL SKETCHES.avif",
              "major": 6,
              "minor": 0
            }
          ],
          "count": 6,
          "items": [
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/1 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "1 DETECTIVE SMOK.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/2 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "2 DETECTIVE SMOK.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/3 DETECTIVE SMOK.avif",
              "type": "image",
              "name": "3 DETECTIVE SMOK.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/4 BG STUDY.avif",
              "type": "image",
              "name": "4 BG STUDY.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/5 BG STUDY.avif",
              "type": "image",
              "name": "5 BG STUDY.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/VISUAL DEVELOPMENT/4. MISCELLANEOUS/6 PENCIL SKETCHES.avif",
              "type": "image",
              "name": "6 PENCIL SKETCHES.avif",
              "major": 6,
              "minor": 0
            }
          ],
          "groups": []
        }
      ]
    },
    {
      "slug": "illustration",
      "title": "Illustration",
      "page": "/html/illustration.html",
      "cover": "/images/ILLUSTRATION/1. LIFE DRAWING/1 life drawing.avif",
      "projects": [
        {
          "slug": "life-drawing",
          "name": "1. LIFE DRAWING",
          "title": "Life Drawing",
          "dir": "/images/ILLUSTRATION/1. LIFE DRAWING",
          "preview": [
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/1 life drawing.avif",
              "type": "image",
              "name": "1 life drawing.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/2 life drawing.avif",
              "type": "image",
              "name": "2 life drawing.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/3 life drawing.avif",
              "type": "image",
              "name": "3 life drawing.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/4 life drawing.avif",
              "type": "image",
              "name": "4 life drawing.avif",
              "major": 4,
              "minor": 0
            }
          ],
          "count": 4,
          "items": [
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/1 life drawing.avif",
              "type": "image",
              "name": "1 life drawing.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/2 life drawing.avif",
              "type": "image",
              "name": "2 life drawing.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/3 life drawing.avif",
              "type": "image",
              "name": "3 life drawing.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/1. LIFE DRAWING/4 life drawing.avif",
              "type": "image",
              "name": "4 life drawing.avif",
              "major": 4,
              "minor": 0
            }
          ],
          "groups": []
        },
        {
          "slug": "traditional-media",
          "name": "2. TRADITIONAL MEDIA",
          "title": "Traditional Media",
          "dir": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA",
          "preview": [
            {
              "src": "/images/ILLUSTRATION/preview/2. TRADITIONAL MEDIA/1 illustrazione.avif",
              "type": "image",
              "name": "1 illustrazione.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/2 illustrazione.avif",
              "type": "image",
              "name": "2 illustrazione.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/3 illustrazione.avif",
              "type": "image",
              "name": "3 illustrazione.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/4 illustrazione.avif",
              "type": "image",
              "name": "4 illustrazione.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/5 illustrazione.avif",
              "type": "image",
              "name": "5 illustrazione.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/6 illustrazione.avif",
              "type": "image",
              "name": "6 illustrazione.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/7 illustrazione.avif",
              "type": "image",
              "name": "7 illustrazione.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/8 illustrazione.avif",
              "type": "image",
              "name": "8 illustrazione.avif",
              "major": 8,
              "minor": 0
            }
          ],
          "count": 8,
          "items": [
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/1 illustrazione.avif",
              "type": "image",
              "name": "1 illustrazione.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/2 illustrazione.avif",
              "type": "image",
              "name": "2 illustrazione.avif",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/3 illustrazione.avif",
              "type": "image",
              "name": "3 illustrazione.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/4 illustrazione.avif",
              "type": "image",
              "name": "4 illustrazione.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/5 illustrazione.avif",
              "type": "image",
              "name": "5 illustrazione.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/6 illustrazione.avif",
              "type": "image",
              "name": "6 illustrazione.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/7 illustrazione.avif",
              "type": "image",
              "name": "7 illustrazione.avif",
              "major": 7,
              "minor": 0
            },
            {
              "src": "/images/ILLUSTRATION/2. TRADITIONAL MEDIA/8 illustrazione.avif",
              "type": "image",
              "name": "8 illustrazione.avif",
              "major": 8,
              "minor": 0
            }
          ],
          "groups": []
        }
      ]
    },
    {
      "slug": "animation",
      "title": "Animation",
      "page": "/html/animation.html",
      "cover": "/images/ANIMATION/1. DUEL/1 DUEL.mp4",
      "projects": [
        {
          "slug": "duel",
          "name": "1. DUEL",
          "title": "Duel",
          "dir": "/images/ANIMATION/1. DUEL",
          "preview": [
            {
              "src": "/images/ANIMATION/1. DUEL/1 DUEL.mp4",
              "type": "video",
              "name": "1 DUEL.mp4",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/1. DUEL/1.1 DUEL.mp4",
              "type": "video",
              "name": "1.1 DUEL.mp4",
              "major": 1,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/1. DUEL/2 DUEL.mp4",
              "type": "video",
              "name": "2 DUEL.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/1. DUEL/2.1 DUEL.mp4",
              "type": "video",
              "name": "2.1 DUEL.mp4",
              "major": 2,
              "minor": 1
            }
          ],
          "count": 6,
          "items": [
            {
              "src": "/images/ANIMATION/1. DUEL/1 DUEL.mp4",
              "type": "video",
              "name": "1 DUEL.mp4",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/1. DUEL/1.1 DUEL.mp4",
              "type": "video",
              "name": "1.1 DUEL.mp4",
              "major": 1,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/1. DUEL/2 DUEL.mp4",
              "type": "video",
              "name": "2 DUEL.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/1. DUEL/2.1 DUEL.mp4",
              "type": "video",
              "name": "2.1 DUEL.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/1. DUEL/3 DUEL colorscript.avif",
              "type": "image",
              "name": "3 DUEL colorscript.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/1. DUEL/4 DUEL character design.avif",
              "type": "image",
              "name": "4 DUEL character design.avif",
              "major": 4,
              "minor": 0
            }
          ],
          "groups": []
        },
        {
          "slug": "les-legendaires",
          "name": "2. LES LÉGENDAIRES",
          "title": "Les Légendaires",
          "dir": "/images/ANIMATION/2. LES LÉGENDAIRES",
          "preview": [
            {
              "src": "/images/ANIMATION/preview/2. LES LÉGENDAIRES/2 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "2 LES LÉGENDAIRES.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/preview/2. LES LÉGENDAIRES/2.1 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "2.1 LES LÉGENDAIRES.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/4 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "4 LES LÉGENDAIRES.mp4",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/6 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "6 LES LÉGENDAIRES.mp4",
              "major": 6,
              "minor": 0
            }
          ],
          "count": 7,
          "items": [
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/1 LES LÉGENDAIRES.avif",
              "type": "image",
              "name": "1 LES LÉGENDAIRES.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/2 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "2 LES LÉGENDAIRES.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/2.1 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "2.1 LES LÉGENDAIRES.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/3 LES LÉGENDAIRES.avif",
              "type": "image",
              "name": "3 LES LÉGENDAIRES.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/4 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "4 LES LÉGENDAIRES.mp4",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/5 LES LÉGENDAIRES.avif",
              "type": "image",
              "name": "5 LES LÉGENDAIRES.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/2. LES LÉGENDAIRES/6 LES LÉGENDAIRES.mp4",
              "type": "video",
              "name": "6 LES LÉGENDAIRES.mp4",
              "major": 6,
              "minor": 0
            }
          ],
          "groups": []
        },
        {
          "slug": "rainy-day",
          "name": "3. RAINY DAY",
          "title": "Rainy Day",
          "dir": "/images/ANIMATION/3. RAINY DAY",
          "preview": [
            {
              "src": "/images/ANIMATION/preview/3. RAINY DAY/1 RAINY DAY.mp4",
              "type": "video",
              "name": "1 RAINY DAY.mp4",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/preview/3. RAINY DAY/1.1 RAINY DAY.mp4",
              "type": "video",
              "name": "1.1 RAINY DAY.mp4",
              "major": 1,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/2 RAINY DAY.mp4",
              "type": "video",
              "name": "2 RAINY DAY.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/2.1 RAINY DAY.mp4",
              "type": "video",
              "name": "2.1 RAINY DAY.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/3 RAINY DAY.mp4",
              "type": "video",
              "name": "3 RAINY DAY.mp4",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/3.1 RAINY DAY.mp4",
              "type": "video",
              "name": "3.1 RAINY DAY.mp4",
              "major": 3,
              "minor": 1
            }
          ],
          "count": 10,
          "items": [
            {
              "src": "/images/ANIMATION/3. RAINY DAY/1 RAINY DAY.mp4",
              "type": "video",
              "name": "1 RAINY DAY.mp4",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/1.1 RAINY DAY.mp4",
              "type": "video",
              "name": "1.1 RAINY DAY.mp4",
              "major": 1,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/2 RAINY DAY.mp4",
              "type": "video",
              "name": "2 RAINY DAY.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/2.1 RAINY DAY.mp4",
              "type": "video",
              "name": "2.1 RAINY DAY.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/3 RAINY DAY.mp4",
              "type": "video",
              "name": "3 RAINY DAY.mp4",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/3.1 RAINY DAY.mp4",
              "type": "video",
              "name": "3.1 RAINY DAY.mp4",
              "major": 3,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/4 RAINY DAY.avif",
              "type": "image",
              "name": "4 RAINY DAY.avif",
              "major": 4,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/5 RAINY DAY.avif",
              "type": "image",
              "name": "5 RAINY DAY.avif",
              "major": 5,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/6 RAINY DAY.avif",
              "type": "image",
              "name": "6 RAINY DAY.avif",
              "major": 6,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/3. RAINY DAY/7 RAINY DAY.avif",
              "type": "image",
              "name": "7 RAINY DAY.avif",
              "major": 7,
              "minor": 0
            }
          ],
          "groups": []
        },
        {
          "slug": "skechy-notes",
          "name": "4. SKECHY NOTES",
          "title": "Skechy Notes",
          "dir": "/images/ANIMATION/4. SKECHY NOTES",
          "preview": [
            {
              "src": "/images/ANIMATION/preview/4. SKECHY NOTES/2 SKETCHY NOTES.mp4",
              "type": "video",
              "name": "2 SKETCHY NOTES.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/preview/4. SKECHY NOTES/2.1 SKETCHY NOTES.mp4",
              "type": "video",
              "name": "2.1 SKETCHY NOTES.mp4",
              "major": 2,
              "minor": 1
            }
          ],
          "count": 5,
          "items": [
            {
              "src": "/images/ANIMATION/4. SKECHY NOTES/1 SKETCHY NOTES.avif",
              "type": "image",
              "name": "1 SKETCHY NOTES.avif",
              "major": 1,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/4. SKECHY NOTES/2 SKETCHY NOTES.mp4",
              "type": "video",
              "name": "2 SKETCHY NOTES.mp4",
              "major": 2,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/4. SKECHY NOTES/2.1 SKETCHY NOTES.mp4",
              "type": "video",
              "name": "2.1 SKETCHY NOTES.mp4",
              "major": 2,
              "minor": 1
            },
            {
              "src": "/images/ANIMATION/4. SKECHY NOTES/3 SKETCHY NOTES.avif",
              "type": "image",
              "name": "3 SKETCHY NOTES.avif",
              "major": 3,
              "minor": 0
            },
            {
              "src": "/images/ANIMATION/4. SKECHY NOTES/4 SKETCHY NOTES.avif",
              "type": "image",
              "name": "4 SKETCHY NOTES.avif",
              "major": 4,
              "minor": 0
            }
          ],
          "groups": []
        }
      ]
    }
  ]
};
